version: '3'

services:
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ems
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
